# Generated by Django 5.0 on 2024-02-13 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0003_alter_area_area_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='end_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='営業終了時間'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='headcount',
            field=models.PositiveIntegerField(default=1, verbose_name='人数'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='start_hour',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='営業開始時間'),
        ),
    ]
