# Generated by Django 5.0 on 2024-02-19 09:39

import nagoyameshi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagoyameshi', '0004_restaurant_end_hour_restaurant_headcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='scheduled_date',
            field=models.DateTimeField(validators=[nagoyameshi.models.scheduled_date_check], verbose_name='予約日'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='headcount',
            field=models.PositiveIntegerField(default=1, verbose_name='最大予約可能人数'),
        ),
    ]
